(in-package #:mime-protocol)

(defparameter *mime-extensions*
  (let ((ht (make-hash-table :test #'equal)))
    (dolist (pair '(("txt" . "text/plain")
                    ("text" . "text/plain")
                    ("html" . "text/html")
                    ("htm" . "text/html")
                    ("css" . "text/css")
                    ("csv" . "text/csv")
                    ("md" . "text/markdown")
                    ("xml" . "application/xml")
                    ("json" . "application/json")
                    ("ndjson" . "application/x-ndjson")
                    ("yaml" . "application/yaml")
                    ("yml" . "application/yaml")
                    ("js" . "text/javascript")
                    ("mjs" . "text/javascript")
                    ("pdf" . "application/pdf")
                    ("zip" . "application/zip")
                    ("gz" . "application/gzip")
                    ("tar" . "application/x-tar")
                    ("wasm" . "application/wasm")
                    ("bin" . "application/octet-stream")
                    ("cbor" . "application/cbor")
                    ("avro" . "application/avro")
                    ("msgpack" . "application/msgpack")
                    ("mpk" . "application/msgpack")
                    ("png" . "image/png")
                    ("jpg" . "image/jpeg")
                    ("jpeg" . "image/jpeg")
                    ("gif" . "image/gif")
                    ("webp" . "image/webp")
                    ("svg" . "image/svg+xml")
                    ("ico" . "image/x-icon")
                    ("mp3" . "audio/mpeg")
                    ("mp4" . "video/mp4")
                    ("woff" . "font/woff")
                    ("woff2" . "font/woff2")
                    ("ttf" . "font/ttf")
                    ("form" . "application/x-www-form-urlencoded")))
      (setf (gethash (car pair) ht) (cdr pair)))
    ht))

(defun %extension-of (name)
  (let* ((s (string-downcase (etypecase name
                               (pathname (file-namestring name))
                               (string name))))
         (dot (position #\. s :from-end t)))
    (if dot
        (subseq s (1+ dot))
        (if (find #\/ s)
            nil
            s))))

(defun lookup-mime (name &optional (default "application/octet-stream"))
  "Filename, pathname, or extension → media-type string."
  (or (gethash (%extension-of name) *mime-extensions*)
      default))

(defun mime-type (name &optional (default "application/octet-stream"))
  "Alias of LOOKUP-MIME."
  (lookup-mime name default))
